{{- if and .Values.rbac.create .Values.rbac.pspEnabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "common.names.fullname" . }}-psp
  labels: {{- include "common.labels.standard" . | nindent 4 }}
rules:
  - apiGroups: ['extensions']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames:
      - {{ template "common.names.fullname" . }}
{{- end }}
