annotations:
  category: ProjectManagement
apiVersion: v2
appVersion: 2020.42.0
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 9.x.x
description: Collection of open source web applications that help software companies build better software.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/phabricator
icon: https://bitnami.com/assets/stacks/phabricator/img/phabricator-stack-110x117.png
keywords:
  - phabricator
  - http
  - https
  - web
  - application
  - collaboration
  - project management
  - bug tracking
  - code review
  - wiki
  - git
  - mercurial
  - subversion
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: phabricator
sources:
  - https://github.com/bitnami/bitnami-docker-phabricator
  - https://www.phacility.com/phabricator/
version: 10.1.1
